// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package creativemaybeno.wakelock;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<Object>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  /**
   * Message for toggling the wakelock on the platform side.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class ToggleMessage {
    private @Nullable Boolean enable;

    public @Nullable Boolean getEnable() {
      return enable;
    }

    public void setEnable(@Nullable Boolean setterArg) {
      this.enable = setterArg;
    }

    public static final class Builder {

      private @Nullable Boolean enable;

      public @NonNull Builder setEnable(@Nullable Boolean setterArg) {
        this.enable = setterArg;
        return this;
      }

      public @NonNull ToggleMessage build() {
        ToggleMessage pigeonReturn = new ToggleMessage();
        pigeonReturn.setEnable(enable);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(1);
      toListResult.add(enable);
      return toListResult;
    }

    static @NonNull ToggleMessage fromList(@NonNull ArrayList<Object> list) {
      ToggleMessage pigeonResult = new ToggleMessage();
      Object enable = list.get(0);
      pigeonResult.setEnable((Boolean) enable);
      return pigeonResult;
    }
  }

  /**
   * Message for reporting the wakelock state from the platform side.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class IsEnabledMessage {
    private @Nullable Boolean enabled;

    public @Nullable Boolean getEnabled() {
      return enabled;
    }

    public void setEnabled(@Nullable Boolean setterArg) {
      this.enabled = setterArg;
    }

    public static final class Builder {

      private @Nullable Boolean enabled;

      public @NonNull Builder setEnabled(@Nullable Boolean setterArg) {
        this.enabled = setterArg;
        return this;
      }

      public @NonNull IsEnabledMessage build() {
        IsEnabledMessage pigeonReturn = new IsEnabledMessage();
        pigeonReturn.setEnabled(enabled);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(1);
      toListResult.add(enabled);
      return toListResult;
    }

    static @NonNull IsEnabledMessage fromList(@NonNull ArrayList<Object> list) {
      IsEnabledMessage pigeonResult = new IsEnabledMessage();
      Object enabled = list.get(0);
      pigeonResult.setEnabled((Boolean) enabled);
      return pigeonResult;
    }
  }

  private static class WakelockApiCodec extends StandardMessageCodec {
    public static final WakelockApiCodec INSTANCE = new WakelockApiCodec();

    private WakelockApiCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 128:
          return IsEnabledMessage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 129:
          return ToggleMessage.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof IsEnabledMessage) {
        stream.write(128);
        writeValue(stream, ((IsEnabledMessage) value).toList());
      } else if (value instanceof ToggleMessage) {
        stream.write(129);
        writeValue(stream, ((ToggleMessage) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface WakelockApi {

    void toggle(@NonNull ToggleMessage msg);

    @NonNull 
    IsEnabledMessage isEnabled();

    /** The codec used by WakelockApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return WakelockApiCodec.INSTANCE;
    }
    /**Sets up an instance of `WakelockApi` to handle messages through the `binaryMessenger`. */
    static void setup(@NonNull BinaryMessenger binaryMessenger, @Nullable WakelockApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.WakelockApi.toggle", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                ToggleMessage msgArg = (ToggleMessage) args.get(0);
                try {
                  api.toggle(msgArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.WakelockApi.isEnabled", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                try {
                  IsEnabledMessage output = api.isEnabled();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
