name: wakelock
description: >-2
  Plugin that allows you to keep the device screen awake, i.e. prevent the screen from sleeping on
  Android, iOS, macOS, Windows, and web.
version: 0.6.2
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock
publish_to: none

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.9.1

  wakelock_macos:
    git: 
      url: https://github.com/pn-smcom/wakelock
      path: wakelock_macos
      ref: dependency_changes2
  wakelock_platform_interface:
    git: 
      url: https://github.com/pn-smcom/wakelock
      path: wakelock_platform_interface
      ref: dependency_changes2
  wakelock_web:
    git: 
      url: https://github.com/pn-smcom/wakelock
      path: wakelock_web
      ref: dependency_changes2
  wakelock_windows:
    git: 
      url: https://github.com/pn-smcom/wakelock
      path: wakelock_windows
      ref: dependency_changes2  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  pigeon: ^10.0.0 # flutter pub run pigeon --input "pigeons/messages.dart"

flutter:
  plugin:
    platforms:
      android:
        package: creativemaybeno.wakelock
        pluginClass: WakelockPlugin
      ios:
        pluginClass: WakelockPlugin
      macos:
        default_package: wakelock_macos
      windows:
        default_package: wakelock_windows
      web:
        default_package: wakelock_web
